from dataclasses import dataclass
from typing import List
from operator import itemgetter

from .element import Element
from .function import Function
from .constant import Constant
from .signal import Signal
from .member import Member
from .enumeration import Enumeration


@dataclass
class GDScriptClass(Element):
    extends: str
    path: str
    functions: List[Function]
    members: List[Member]
    constants: List[Constant]
    signals: List[Signal]
    enums: List[Enumeration]
    sub_classes: List["GDScriptClass"]
    category: str

    def __post_init__(self):
        super().__post_init__()

        if "category" in self.metadata:
            self.category = (
                self.metadata["category"].title()
                if isinstance(self.metadata["category"], str)
                else "Uncategorized"
            )
        elements = self.functions + self.members + self.signals + self.enums
        self.symbols = {element.name for element in elements}

    @staticmethod
    def from_dict(data: dict):
        # The extends_class field is a list in json even though
        # it only has one class.
        extends: str = data["extends_class"][0] if data["extends_class"] else ""

        enumerations = []
        for entry in data["constants"]:
            if (
                entry["data_type"] == "Dictionary"
                and all(isinstance(v, int) for v in entry["value"].values())
                and not entry["name"].startswith("_")
            ):
                # Got a enum
                enumeration = Enumeration.from_dict(entry)
                if enumeration.hidden:
                    continue
                enumerations.append(enumeration)

        sub_classes = []
        for entry in data["sub_classes"]:
            sub_class = GDScriptClass.from_dict(entry)
            if sub_class.hidden:
                continue
            sub_classes.append(sub_class)

        return GDScriptClass(
            "",  # Signature
            data["name"],
            data["description"],
            extends,
            data["path"],
            _get_functions(data["methods"])
            + _get_functions(data["static_functions"], is_static=True),
            _get_members(data["members"]),
            _get_constants(data["constants"]),
            _get_signals(data["signals"]),
            enumerations,
            sub_classes,
            "Uncategorized",
        )

    def get_extends_tree(self, classes: "GDScriptClasses") -> List[str]:
        """
        Returns the list of ancestors for this class, starting from self.extends.

        Arguments:
        - classes: a GDScriptClasses list of GDScriptClass this object is part of.
        """
        extends: str = self.extends
        extends_tree: List[str] = []
        while extends != "":
            extends_tree.append(extends)
            extends = next((cls.extends for cls in classes if cls.name == extends), "")
        return extends_tree


def _get_signals(data: List[dict]) -> List[Signal]:
    return list(
        filter(
            lambda signal: not signal.hidden,
            [Signal.from_dict(entry) for entry in data],
        )
    )


def _get_constants(constants_data: List[dict]) -> List[Constant]:
    """
    Filters and distinguishes constants from enums.
    """

    def is_not_enum(constant):
        """
        Returns `True` if the constant's source data doesn't correspond to an enum.
        That is, if it's not a dictionary with only a list of named integers.
        """
        is_enum = constant["data_type"] == "Dictionary"
        is_enum = is_enum and all(
            isinstance(value, int) for value in constant["value"].values()
        )
        return not is_enum

    _constants = filter(lambda c: not c["name"].startswith("_"), constants_data)
    _constants = filter(is_not_enum, _constants)
    _constants = sorted(_constants, key=itemgetter("name"))

    constants: List[Constant] = list(map(lambda c: Constant.from_dict(c), _constants))
    return list(filter(lambda c: not c.hidden, constants))


def _get_members(data: List[dict]) -> List[Member]:
    return list(
        filter(
            lambda member: not member.hidden,
            [
                Member.from_dict(entry)
                for entry in data
                if not entry["name"].startswith("_")
            ],
        )
    )


def _get_functions(data: List[dict], is_static: bool = False) -> List[Function]:
    """
    Returns a list of valid functions to put in the class reference. Skips
    built-in virtual callbacks, except for constructor functions marked for
    inclusion, and private methods.
    """
    functions: List[Function] = []
    for entry in data:
        name: str = entry["name"]

        # Skip built-in virtual callbacks
        if name in BUILTIN_VIRTUAL_CALLBACKS:
            continue

        # Skip _init() if no arguments
        if name == TYPE_CONSTRUCTOR and not entry["arguments"]:
            continue

        function = Function.from_dict(entry, is_static)

        is_private: bool = (
            name.startswith("_")
            and "is_virtual" not in function.metadata
            and name != TYPE_CONSTRUCTOR
        )

        if is_private or function.hidden:
            continue

        functions.append(function)
    return functions


BUILTIN_VIRTUAL_CALLBACKS = [
    "_process",
    "_physics_process",
    "_input",
    "_unhandled_input",
    "_gui_input",
    "_draw",
    "_get_configuration_warning",
    "_ready",
    "_enter_tree",
    "_exit_tree",
    "_get",
    "_get_property_list",
    "_notification",
    "_set",
    "_to_string",
    "_clips_input",
    "_get_minimum_size",
    "_gui_input",
    "_make_custom_tooltip",
]

TYPE_CONSTRUCTOR = "_init"

BUILTIN_CLASSES = [
    "aabb",
    "acceptdialog",
    "aescontext",
    "animatedsprite",
    "animatedsprite3d",
    "animatedtexture",
    "animation",
    "animationnode",
    "animationnodeadd2",
    "animationnodeadd3",
    "animationnodeanimation",
    "animationnodeblend2",
    "animationnodeblend3",
    "animationnodeblendspace1d",
    "animationnodeblendspace2d",
    "animationnodeblendtree",
    "animationnodeoneshot",
    "animationnodeoutput",
    "animationnodestatemachine",
    "animationnodestatemachineplayback",
    "animationnodestatemachinetransition",
    "animationnodetimescale",
    "animationnodetimeseek",
    "animationnodetransition",
    "animationplayer",
    "animationrootnode",
    "animationtrackeditplugin",
    "animationtree",
    "animationtreeplayer",
    "area",
    "area2d",
    "array",
    "arraymesh",
    "arvranchor",
    "arvrcamera",
    "arvrcontroller",
    "arvrinterface",
    "arvrinterfacegdnative",
    "arvrorigin",
    "arvrpositionaltracker",
    "arvrserver",
    "aspectratiocontainer",
    "astar",
    "astar2d",
    "atlastexture",
    "audiobuslayout",
    "audioeffect",
    "audioeffectamplify",
    "audioeffectbandlimitfilter",
    "audioeffectbandpassfilter",
    "audioeffectcapture",
    "audioeffectchorus",
    "audioeffectcompressor",
    "audioeffectdelay",
    "audioeffectdistortion",
    "audioeffecteq",
    "audioeffecteq10",
    "audioeffecteq21",
    "audioeffecteq6",
    "audioeffectfilter",
    "audioeffecthighpassfilter",
    "audioeffecthighshelffilter",
    "audioeffectinstance",
    "audioeffectlimiter",
    "audioeffectlowpassfilter",
    "audioeffectlowshelffilter",
    "audioeffectnotchfilter",
    "audioeffectpanner",
    "audioeffectphaser",
    "audioeffectpitchshift",
    "audioeffectrecord",
    "audioeffectreverb",
    "audioeffectspectrumanalyzer",
    "audioeffectspectrumanalyzerinstance",
    "audioeffectstereoenhance",
    "audioserver",
    "audiostream",
    "audiostreamgenerator",
    "audiostreamgeneratorplayback",
    "audiostreammicrophone",
    "audiostreammp3",
    "audiostreamoggvorbis",
    "audiostreamplayback",
    "audiostreamplaybackresampled",
    "audiostreamplayer",
    "audiostreamplayer2d",
    "audiostreamplayer3d",
    "audiostreamrandompitch",
    "audiostreamsample",
    "backbuffercopy",
    "bakedlightmap",
    "bakedlightmapdata",
    "basebutton",
    "basis",
    "bitmap",
    "bitmapfont",
    "bone2d",
    "boneattachment",
    "bool",
    "boxcontainer",
    "boxshape",
    "button",
    "buttongroup",
    "camera",
    "camera2d",
    "camerafeed",
    "cameraserver",
    "cameratexture",
    "canvasitem",
    "canvasitemmaterial",
    "canvaslayer",
    "canvasmodulate",
    "capsulemesh",
    "capsuleshape",
    "capsuleshape2d",
    "centercontainer",
    "charfxtransform",
    "checkbox",
    "checkbutton",
    "circleshape2d",
    "classdb",
    "clippedcamera",
    "collisionobject",
    "collisionobject2d",
    "collisionpolygon",
    "collisionpolygon2d",
    "collisionshape",
    "collisionshape2d",
    "color",
    "colorpicker",
    "colorpickerbutton",
    "colorrect",
    "concavepolygonshape",
    "concavepolygonshape2d",
    "conetwistjoint",
    "configfile",
    "confirmationdialog",
    "container",
    "control",
    "convexpolygonshape",
    "convexpolygonshape2d",
    "cpuparticles",
    "cpuparticles2d",
    "crypto",
    "cryptokey",
    "csgbox",
    "csgcombiner",
    "csgcylinder",
    "csgmesh",
    "csgpolygon",
    "csgprimitive",
    "csgshape",
    "csgsphere",
    "csgtorus",
    "csharpscript",
    "cubemap",
    "cubemesh",
    "cullinstance",
    "curve",
    "curve2d",
    "curve3d",
    "curvetexture",
    "cylindermesh",
    "cylindershape",
    "dampedspringjoint2d",
    "dictionary",
    "directionallight",
    "directory",
    "dtlsserver",
    "dynamicfont",
    "dynamicfontdata",
    "editorexportplugin",
    "editorfeatureprofile",
    "editorfiledialog",
    "editorfilesystem",
    "editorfilesystemdirectory",
    "editorimportplugin",
    "editorinspector",
    "editorinspectorplugin",
    "editorinterface",
    "editornavigationmeshgenerator",
    "editorplugin",
    "editorproperty",
    "editorresourceconversionplugin",
    "editorresourcepicker",
    "editorresourcepreview",
    "editorresourcepreviewgenerator",
    "editorsceneimporter",
    "editorsceneimporterfbx",
    "editorsceneimportergltf",
    "editorscenepostimport",
    "editorscript",
    "editorscriptpicker",
    "editorselection",
    "editorsettings",
    "editorspatialgizmo",
    "editorspatialgizmoplugin",
    "editorspinslider",
    "editorvcsinterface",
    "encodedobjectasid",
    "engine",
    "environment",
    "expression",
    "externaltexture",
    "file",
    "filedialog",
    "filesystemdock",
    "float",
    "font",
    "funcref",
    "gdnative",
    "gdnativelibrary",
    "gdscript",
    "gdscriptfunctionstate",
    "generic6dofjoint",
    "geometry",
    "geometryinstance",
    "giprobe",
    "giprobedata",
    "gltfaccessor",
    "gltfanimation",
    "gltfbufferview",
    "gltfcamera",
    "gltfdocument",
    "gltflight",
    "gltfmesh",
    "gltfnode",
    "gltfskeleton",
    "gltfskin",
    "gltfspecgloss",
    "gltfstate",
    "gltftexture",
    "godotsharp",
    "gradient",
    "gradienttexture",
    "graphedit",
    "graphnode",
    "gridcontainer",
    "gridmap",
    "groovejoint2d",
    "hashingcontext",
    "hboxcontainer",
    "heightmapshape",
    "hingejoint",
    "hmaccontext",
    "hscrollbar",
    "hseparator",
    "hslider",
    "hsplitcontainer",
    "httpclient",
    "httprequest",
    "image",
    "imagetexture",
    "immediategeometry",
    "input",
    "inputevent",
    "inputeventaction",
    "inputeventgesture",
    "inputeventjoypadbutton",
    "inputeventjoypadmotion",
    "inputeventkey",
    "inputeventmagnifygesture",
    "inputeventmidi",
    "inputeventmouse",
    "inputeventmousebutton",
    "inputeventmousemotion",
    "inputeventpangesture",
    "inputeventscreendrag",
    "inputeventscreentouch",
    "inputeventwithmodifiers",
    "inputmap",
    "instanceplaceholder",
    "int",
    "interpolatedcamera",
    "ip",
    "itemlist",
    "javaclass",
    "javaclasswrapper",
    "javascript",
    "javascriptobject",
    "jnisingleton",
    "joint",
    "joint2d",
    "json",
    "jsonparseresult",
    "jsonrpc",
    "kinematicbody",
    "kinematicbody2d",
    "kinematiccollision",
    "kinematiccollision2d",
    "label",
    "largetexture",
    "light",
    "light2d",
    "lightoccluder2d",
    "line2d",
    "lineedit",
    "lineshape2d",
    "linkbutton",
    "listener",
    "listener2d",
    "mainloop",
    "margincontainer",
    "marshalls",
    "material",
    "menubutton",
    "mesh",
    "meshdatatool",
    "meshinstance",
    "meshinstance2d",
    "meshlibrary",
    "meshtexture",
    "mobilevrinterface",
    "multimesh",
    "multimeshinstance",
    "multimeshinstance2d",
    "multiplayerapi",
    "multiplayerpeergdnative",
    "mutex",
    "nativescript",
    "navigation",
    "navigation2d",
    "navigationmesh",
    "navigationmeshinstance",
    "navigationpolygon",
    "navigationpolygoninstance",
    "networkedmultiplayerenet",
    "networkedmultiplayerpeer",
    "ninepatchrect",
    "node",
    "node2d",
    "nodepath",
    "noisetexture",
    "object",
    "occluder",
    "occluderpolygon2d",
    "occludershape",
    "occludershapesphere",
    "omnilight",
    "opensimplexnoise",
    "optionbutton",
    "os",
    "packeddatacontainer",
    "packeddatacontainerref",
    "packedscene",
    "packedscenegltf",
    "packetpeer",
    "packetpeerdtls",
    "packetpeergdnative",
    "packetpeerstream",
    "packetpeerudp",
    "panel",
    "panelcontainer",
    "panoramasky",
    "parallaxbackground",
    "parallaxlayer",
    "particles",
    "particles2d",
    "particlesmaterial",
    "path",
    "path2d",
    "pathfollow",
    "pathfollow2d",
    "pckpacker",
    "performance",
    "phashtranslation",
    "physicalbone",
    "physics2ddirectbodystate",
    "physics2ddirectspacestate",
    "physics2dserver",
    "physics2dshapequeryparameters",
    "physics2dtestmotionresult",
    "physicsbody",
    "physicsbody2d",
    "physicsdirectbodystate",
    "physicsdirectspacestate",
    "physicsmaterial",
    "physicsserver",
    "physicsshapequeryparameters",
    "physicstestmotionresult",
    "pinjoint",
    "pinjoint2d",
    "plane",
    "planemesh",
    "planeshape",
    "pluginscript",
    "pointmesh",
    "polygon2d",
    "polygonpathfinder",
    "poolbytearray",
    "poolcolorarray",
    "poolintarray",
    "poolrealarray",
    "poolstringarray",
    "poolvector2array",
    "poolvector3array",
    "popup",
    "popupdialog",
    "popupmenu",
    "popuppanel",
    "portal",
    "position2d",
    "position3d",
    "primitivemesh",
    "prismmesh",
    "proceduralsky",
    "progressbar",
    "projectsettings",
    "proximitygroup",
    "proxytexture",
    "quadmesh",
    "quat",
    "randomnumbergenerator",
    "range",
    "raycast",
    "raycast2d",
    "rayshape",
    "rayshape2d",
    "rect2",
    "rectangleshape2d",
    "reference",
    "referencerect",
    "reflectionprobe",
    "regex",
    "regexmatch",
    "remotetransform",
    "remotetransform2d",
    "resource",
    "resourceformatloader",
    "resourceformatsaver",
    "resourceimporter",
    "resourceinteractiveloader",
    "resourceloader",
    "resourcepreloader",
    "resourcesaver",
    "richtexteffect",
    "richtextlabel",
    "rid",
    "rigidbody",
    "rigidbody2d",
    "room",
    "roomgroup",
    "roommanager",
    "rootmotionview",
    "scenestate",
    "scenetree",
    "scenetreetimer",
    "script",
    "scriptcreatedialog",
    "scripteditor",
    "scrollbar",
    "scrollcontainer",
    "segmentshape2d",
    "semaphore",
    "separator",
    "shader",
    "shadermaterial",
    "shape",
    "shape2d",
    "shortcut",
    "skeleton",
    "skeleton2d",
    "skeletonik",
    "skin",
    "skinreference",
    "sky",
    "slider",
    "sliderjoint",
    "softbody",
    "spatial",
    "spatialgizmo",
    "spatialmaterial",
    "spatialvelocitytracker",
    "spheremesh",
    "sphereshape",
    "spinbox",
    "splitcontainer",
    "spotlight",
    "springarm",
    "sprite",
    "sprite3d",
    "spritebase3d",
    "spriteframes",
    "staticbody",
    "staticbody2d",
    "streampeer",
    "streampeerbuffer",
    "streampeergdnative",
    "streampeerssl",
    "streampeertcp",
    "streamtexture",
    "string",
    "stylebox",
    "styleboxempty",
    "styleboxflat",
    "styleboxline",
    "styleboxtexture",
    "surfacetool",
    "tabcontainer",
    "tabs",
    "tcp_server",
    "textedit",
    "textfile",
    "texture",
    "texture3d",
    "texturearray",
    "texturebutton",
    "texturelayered",
    "textureprogress",
    "texturerect",
    "theme",
    "thread",
    "tilemap",
    "tileset",
    "timer",
    "toolbutton",
    "touchscreenbutton",
    "transform",
    "transform2d",
    "translation",
    "translationserver",
    "tree",
    "treeitem",
    "trianglemesh",
    "tween",
    "udpserver",
    "undoredo",
    "upnp",
    "upnpdevice",
    "variant",
    "vboxcontainer",
    "vector2",
    "vector3",
    "vehiclebody",
    "vehiclewheel",
    "videoplayer",
    "videostream",
    "videostreamgdnative",
    "videostreamtheora",
    "videostreamwebm",
    "viewport",
    "viewportcontainer",
    "viewporttexture",
    "visibilityenabler",
    "visibilityenabler2d",
    "visibilitynotifier",
    "visibilitynotifier2d",
    "visualinstance",
    "visualscript",
    "visualscriptbasictypeconstant",
    "visualscriptbuiltinfunc",
    "visualscriptclassconstant",
    "visualscriptcomment",
    "visualscriptcomposearray",
    "visualscriptcondition",
    "visualscriptconstant",
    "visualscriptconstructor",
    "visualscriptcustomnode",
    "visualscriptdeconstruct",
    "visualscripteditor",
    "visualscriptemitsignal",
    "visualscriptenginesingleton",
    "visualscriptexpression",
    "visualscriptfunction",
    "visualscriptfunctioncall",
    "visualscriptfunctionstate",
    "visualscriptglobalconstant",
    "visualscriptindexget",
    "visualscriptindexset",
    "visualscriptinputaction",
    "visualscriptiterator",
    "visualscriptlists",
    "visualscriptlocalvar",
    "visualscriptlocalvarset",
    "visualscriptmathconstant",
    "visualscriptnode",
    "visualscriptoperator",
    "visualscriptpreload",
    "visualscriptpropertyget",
    "visualscriptpropertyset",
    "visualscriptresourcepath",
    "visualscriptreturn",
    "visualscriptscenenode",
    "visualscriptscenetree",
    "visualscriptselect",
    "visualscriptself",
    "visualscriptsequence",
    "visualscriptsubcall",
    "visualscriptswitch",
    "visualscripttypecast",
    "visualscriptvariableget",
    "visualscriptvariableset",
    "visualscriptwhile",
    "visualscriptyield",
    "visualscriptyieldsignal",
    "visualserver",
    "visualshader",
    "visualshadernode",
    "visualshadernodebooleanconstant",
    "visualshadernodebooleanuniform",
    "visualshadernodecolorconstant",
    "visualshadernodecolorfunc",
    "visualshadernodecolorop",
    "visualshadernodecoloruniform",
    "visualshadernodecompare",
    "visualshadernodecubemap",
    "visualshadernodecubemapuniform",
    "visualshadernodecustom",
    "visualshadernodedeterminant",
    "visualshadernodedotproduct",
    "visualshadernodeexpression",
    "visualshadernodefaceforward",
    "visualshadernodefresnel",
    "visualshadernodeglobalexpression",
    "visualshadernodegroupbase",
    "visualshadernodeif",
    "visualshadernodeinput",
    "visualshadernodeis",
    "visualshadernodeouterproduct",
    "visualshadernodeoutput",
    "visualshadernodescalarclamp",
    "visualshadernodescalarconstant",
    "visualshadernodescalarderivativefunc",
    "visualshadernodescalarfunc",
    "visualshadernodescalarinterp",
    "visualshadernodescalarop",
    "visualshadernodescalarsmoothstep",
    "visualshadernodescalarswitch",
    "visualshadernodescalaruniform",
    "visualshadernodeswitch",
    "visualshadernodetexture",
    "visualshadernodetextureuniform",
    "visualshadernodetextureuniformtriplanar",
    "visualshadernodetransformcompose",
    "visualshadernodetransformconstant",
    "visualshadernodetransformdecompose",
    "visualshadernodetransformfunc",
    "visualshadernodetransformmult",
    "visualshadernodetransformuniform",
    "visualshadernodetransformvecmult",
    "visualshadernodeuniform",
    "visualshadernodeuniformref",
    "visualshadernodevec3constant",
    "visualshadernodevec3uniform",
    "visualshadernodevectorclamp",
    "visualshadernodevectorcompose",
    "visualshadernodevectordecompose",
    "visualshadernodevectorderivativefunc",
    "visualshadernodevectordistance",
    "visualshadernodevectorfunc",
    "visualshadernodevectorinterp",
    "visualshadernodevectorlen",
    "visualshadernodevectorop",
    "visualshadernodevectorrefract",
    "visualshadernodevectorscalarmix",
    "visualshadernodevectorscalarsmoothstep",
    "visualshadernodevectorscalarstep",
    "visualshadernodevectorsmoothstep",
    "vscrollbar",
    "vseparator",
    "vslider",
    "vsplitcontainer",
    "weakref",
    "webrtcdatachannel",
    "webrtcdatachannelgdnative",
    "webrtcmultiplayer",
    "webrtcpeerconnection",
    "webrtcpeerconnectiongdnative",
    "websocketclient",
    "websocketmultiplayerpeer",
    "websocketpeer",
    "websocketserver",
    "webxrinterface",
    "windowdialog",
    "world",
    "world2d",
    "worldenvironment",
    "x509certificate",
    "xmlparser",
    "ysort",
]
